apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
        - name: app
          image: 'image-registry.openshift-image-registry.svc:5000/ocooman-dev/my-python-app:latest'
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
